### ISSUE TITLE
Login redirect

### ISSUE THREAD

**Issue by staab** [coracle-social/flotilla#15]
Add redirect on successful login to the page they originally were going for

**Comment by buttercat1791** [comment]
I'll pick this up, if it's still open.

**Comment by staab** [comment]
Go for it!

**Comment by staab** [comment]
@buttercat1791 hopefully I haven't put you out, but I was in the midst of fixing some bugs with modals and history, and I think I fixed this issue in the process. Now, when you visit the app at a particular url, it doesn't change the url on login.

**Comment by buttercat1791** [comment]
Oh sweet!  Out of curiosity, how'd you end up doing it?  I was trying this morning to work with browser history, but was having a hard time keeping track of state across history pushes.

**Comment by staab** [comment]
Let me tell you, keeping track of history across pages and modals is a nightmare. Coracle uses nested modals heavily, so I've done a lot with it and I still haven't figured out how to do it "right". But in this case it was actually very simple, I just made the layout show something else based on logged in user, without modifying the url at all. So once the user logs in, they're on the page they had navigated to.
