### ISSUE TITLE
NIP-46 support is broken

### ISSUE THREAD

**Issue by 42Pupusas** [coracle-social/flotilla#80]
Tried logging in using my personal bunker. 

Looks the implementations of NIP46 are broken: 

- The flow ignores the relays provided by the user and ONLY sends the request through `relay.nsec.app`

- The request does not use NIP-04 encryption as described in the NIP (not sure which one its using as I tried NIP-44 and it also didn't work.

**Comment by staab** [comment]
Just released an update, which should fix the relay selection issue. NIP 46 implementations are in the process of switching to NIP 44, which seems to be covered by most implementations. I suggest you update your signer if possible.
